<#
.SYNOPSIS
    Tests for tools\New-ScanReport.ps1. Runs on Linux under pwsh 7 and on Windows PowerShell 5.1.

.DESCRIPTION
    Asserts against the -PassThru summary object wherever possible; the HTML is only inspected
    where the assertion is genuinely about markup (script-block survival). Fixtures:

      fixtures\run_small.json   hand-written, every severity, the awkward shapes
      fixtures\run_large.json   generated by New-ZbLargeRunFixture below (1,200 findings);
                                regenerated automatically if missing

    The technique-map fixture and the comparison baseline are derived at run time into a temp
    directory, so the shipped fixture list stays exactly what the task brief names.

    Exit code is non-zero when any assertion fails.

.EXAMPLE
    pwsh tools/tests/Test-ScanReport.ps1
#>
[CmdletBinding()]
param()

$ErrorActionPreference = 'Stop'

# --------------------------------------------------------------------------------------------
# Tiny assertion helpers (G7 will supply the shared library; this file must stand alone)
# --------------------------------------------------------------------------------------------

$script:ZbPass = 0
$script:ZbFail = 0
$script:ZbFailures = @()

function Assert-ZbTrue {
    param([bool]$Condition, [string]$Name)
    if ($Condition) {
        $script:ZbPass = $script:ZbPass + 1
        Write-Host ('  ok    ' + $Name)
    }
    else {
        $script:ZbFail = $script:ZbFail + 1
        $script:ZbFailures += $Name
        Write-Host ('  FAIL  ' + $Name)
    }
}

function Assert-ZbEqual {
    param($Expected, $Actual, [string]$Name)
    Assert-ZbTrue -Condition (('' + $Expected) -eq ('' + $Actual)) -Name ($Name + " (expected '$Expected', got '$Actual')")
}

# --------------------------------------------------------------------------------------------
# Locations and scratch space
# --------------------------------------------------------------------------------------------

$here = $PSScriptRoot
$renderer = Join-Path -Path (Split-Path -Path $here -Parent) -ChildPath 'New-ScanReport.ps1'
$fixtureDir = Join-Path -Path $here -ChildPath 'fixtures'
$smallFixture = Join-Path -Path $fixtureDir -ChildPath 'run_small.json'
$largeFixture = Join-Path -Path $fixtureDir -ChildPath 'run_large.json'

$tempDir = Join-Path -Path ([System.IO.Path]::GetTempPath()) -ChildPath ('zbtest_scanreport_' + $PID)
New-Item -ItemType Directory -Path $tempDir -Force | Out-Null
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)

# --------------------------------------------------------------------------------------------
# Technique-map fixture (shape per BLUEPRINT §4, including the _comment documentation keys).
# "Defense Evasion" deliberately maps to nothing in run_small: it must still appear as an
# empty rollup row.
# --------------------------------------------------------------------------------------------

$mapFixture = Join-Path -Path $tempDir -ChildPath 'mitre_mapping.json'
$mapJson = @'
{
  "metadata": { "name": "fixture technique map", "version": "0-test" },
  "tactics": {
    "TA0006": "Credential Access",
    "TA0003": "Persistence",
    "TA0008": "Lateral Movement",
    "TA0002": "Execution",
    "TA0005": "Defense Evasion"
  },
  "techniques": {
    "T1003":     { "name": "OS Credential Dumping", "tactics": ["Credential Access"], "url": "about:blank" },
    "T1547.001": { "name": "Run Keys",              "tactics": ["Persistence"],       "url": "about:blank" },
    "T1021":     { "name": "Remote Services",       "tactics": ["Lateral Movement"],  "url": "about:blank" },
    "T1053":     { "name": "Scheduled Task/Job",    "tactics": ["Execution"],         "url": "about:blank" }
  },
  "threat_type_map": {
    "CREDENTIAL_THEFT": ["T1003"],
    "PERSISTENCE_RUNKEY": ["T1547.001"]
  },
  "keyword_map": {
    "_comment": "documentation key - resolution must skip this",
    "lsass": ["T1003"]
  },
  "phase_map": {
    "_comment": "documentation key - resolution must skip this",
    "74.5": ["T1021"],
    "99": ["T1053"]
  }
}
'@
[System.IO.File]::WriteAllText($mapFixture, $mapJson, $utf8NoBom)

# --------------------------------------------------------------------------------------------
# Large-fixture builder: deterministic (no randomness), 1,200 real findings in a realistic
# severity mix, plus flood-cap markers and a full 133-phase timing table. Regenerates the
# shipped fixtures\run_large.json when it is missing.
# --------------------------------------------------------------------------------------------

function New-ZbLargeRunFixture {
    param([string]$OutPath)

    $threatTypes = @('INVENTORY', 'NETWORK_BEACON', 'PERSISTENCE_RUNKEY', 'CREDENTIAL_THEFT',
        'SERVICE_ODD', 'DRIVER_UNSIGNED', 'ACCOUNT_ANOMALY', 'FIREWALL_GAP')
    $findings = New-Object System.Collections.Generic.List[object]
    $tally = @{}
    for ($i = 1; $i -le 1200; $i++) {
        $sev = 'INFO'
        if ($i % 150 -eq 0) { $sev = 'CRITICAL' }
        elseif ($i % 40 -eq 0) { $sev = 'HIGH' }
        elseif ($i % 3 -eq 0) { $sev = 'POSSIBLE' }
        $phaseNum = 1 + (($i * 7) % 133)
        $phaseLabel = 'PHASE ' + $phaseNum
        if ($phaseNum -eq 74) { $phaseLabel = 'PHASE 74.5' }
        $tt = $threatTypes[$i % $threatTypes.Count]
        if (-not $tally.ContainsKey($tt)) { $tally[$tt] = 0 }
        $tally[$tt] = $tally[$tt] + 1
        $descr = ('Synthetic finding {0}: repeated observation of category {1} on this host.' -f $i, $tt)
        if ($i % 111 -eq 0) { $descr = $descr + ' Hostile text sample: <img src=x onerror=alert(1)> </script> "quoted".' }
        $findings.Add([pscustomobject]@{
                ID          = ('P{0}_{1:x6}' -f $phaseNum, (($i * 2654435761) % 16777216))
                Phase       = $phaseLabel
                ThreatType  = $tt
                Severity    = $sev
                Description = $descr
                Target      = ('C:\Users\client\AppData\Local\synthetic\item_{0}.dat' -f $i)
                FixAction   = 'Info'
                FixParam    = ''
                Group       = $phaseLabel
                Selected    = $false
                Timestamp   = '2026-08-19 15:01:22'
            })
    }
    foreach ($capPhase in @(9, 44, 101)) {
        $findings.Add([pscustomobject]@{
                ID          = ('GROUPCAP_PHASE{0}' -f $capPhase)
                Phase       = ('PHASE {0}' -f $capPhase)
                ThreatType  = 'INVENTORY'
                Severity    = 'INFO'
                Description = ('Group cap reached for PHASE {0}: 100 rows shown, remainder suppressed.' -f $capPhase)
                Target      = ('PHASE {0}' -f $capPhase)
                FixAction   = 'Info'
                FixParam    = ''
                Group       = ('PHASE {0}' -f $capPhase)
                Selected    = $false
                Timestamp   = '2026-08-19 15:01:22'
            })
    }
    $timings = New-Object System.Collections.Generic.List[object]
    for ($p = 1; $p -le 133; $p++) {
        $timings.Add([pscustomobject]@{
                Phase   = ('PHASE {0} — SYNTHETIC CHECK {0}' -f $p)
                Seconds = [math]::Round(((($p * 37) % 240) + 3) / 10.0, 1)
            })
    }
    $record = [pscustomobject]@{
        Timestamp       = '2026-08-19T15:00:00.0000000-04:00'
        Host            = 'WORKSTATION-09'
        User            = 'ACME\tech'
        Mode            = 'DEEP'
        TimeWindow      = 'ALL TIME'
        RiskScore       = 214
        RiskLabel       = 'SEVERE'
        Paranoid        = $false
        Stealth         = $false
        Findings        = $findings.ToArray()
        PhaseTimings    = $timings.ToArray()
        RecoveredErrors = @('PHASE 88: one registry key unreadable; skipped.')
        BaselineDelta   = @()
        ThreatTally     = [pscustomobject]$tally
    }
    $json = ConvertTo-Json -InputObject $record -Depth 6 -Compress
    [System.IO.File]::WriteAllText($OutPath, $json, (New-Object System.Text.UTF8Encoding($false)))
}

if (-not (Test-Path -LiteralPath $largeFixture)) {
    Write-Host 'Generating fixtures/run_large.json (missing)...'
    New-ZbLargeRunFixture -OutPath $largeFixture
}

# --------------------------------------------------------------------------------------------
# Render run_small once: summary, HTML and CSV feed most of the assertions
# --------------------------------------------------------------------------------------------

Write-Host 'run_small render'
$smallOut = Join-Path -Path $tempDir -ChildPath 'small_report.html'
$sum = & $renderer -Path $smallFixture -OutFile $smallOut -MappingPath $mapFixture -Csv -PassThru

# --- 1. Severity counts match the fixture; GROUPCAP_ rows excluded from every count ---
Assert-ZbEqual 12 $sum.TotalFindings 'total findings (flood-cap marker excluded)'
Assert-ZbEqual 1 $sum.GroupCapCount 'flood-cap marker counted as metadata'
Assert-ZbEqual 2 $sum.SeverityCounts.CRITICAL 'CRITICAL count'
Assert-ZbEqual 2 $sum.SeverityCounts.HIGH 'HIGH count'
Assert-ZbEqual 3 $sum.SeverityCounts.POSSIBLE 'POSSIBLE count'
Assert-ZbEqual 4 $sum.SeverityCounts.INFO 'INFO count (GROUPCAP row not counted)'
Assert-ZbEqual 1 $sum.SeverityCounts.OTHER 'unknown severity kept, bucketed as OTHER'
Assert-ZbTrue ($sum.TallyAgrees) 'computed tally agrees with the record ThreatTally'

# --- 2. Tactic rollup totals + unmapped reconcile with the total finding count ---
$rollupSum = 0
foreach ($row in @($sum.TacticRollup)) { $rollupSum = $rollupSum + [int]$row.Total }
Assert-ZbEqual 12 $rollupSum 'rollup rows (incl. Unmapped) sum to total findings'
Assert-ZbEqual 12 ($sum.MappedCount + $sum.UnmappedCount) 'MappedCount + UnmappedCount reconciles'
$rowsByTactic = @{}
foreach ($row in @($sum.TacticRollup)) { $rowsByTactic[$row.Tactic] = $row }
Assert-ZbEqual 2 $rowsByTactic['Credential Access'].Total 'keyword + threat_type map both land in Credential Access'
Assert-ZbEqual 2 $rowsByTactic['Persistence'].Total 'threat_type map resolves Persistence'
Assert-ZbTrue ($rowsByTactic.ContainsKey('Defense Evasion')) 'tactic with no findings still gets a row'
Assert-ZbEqual 0 $rowsByTactic['Defense Evasion'].Total 'empty tactic row shows zero'
Assert-ZbEqual 6 $rowsByTactic['Unmapped'].Total 'unresolved findings land in the explicit Unmapped row'

# --- 3. Fractional phase keys: own key first, integer floor as fallback ---
Assert-ZbEqual 1 $rowsByTactic['Lateral Movement'].Total 'PHASE 74.5 resolves via its own fractional phase_map key'
Assert-ZbEqual 1 $rowsByTactic['Execution'].Total 'PHASE 99.5 falls back to the integer floor key "99"'

# --- 4. A </script> in a description must not terminate the inline script block ---
# Only a raw closing tag can end a script element, so the page must contain exactly the two
# real terminators (data island + behaviour script); a data leak would add a third. The island
# must still parse as JSON and carry the hostile text intact.
$smallHtml = Get-Content -LiteralPath $smallOut -Raw -Encoding UTF8
$closeCount = [regex]::Matches($smallHtml, [regex]::Escape('</script>')).Count
Assert-ZbEqual 2 $closeCount 'exactly two </script> terminators: data cannot end a script block early'
Assert-ZbTrue ($smallHtml.Contains('<\/')) 'embedded JSON uses the <\/ escape'
$islandMatch = [regex]::Match($smallHtml, '<script type="application/json" id="zb-data">(.*?)</script>', 'Singleline')
Assert-ZbTrue ($islandMatch.Success) 'data island present and closed'
$islandOk = $false
$islandCsv = ''
if ($islandMatch.Success) {
    try {
        $island = $islandMatch.Groups[1].Value | ConvertFrom-Json
        $islandOk = $true
        $islandCsv = '' + $island.csv
    }
    catch { $islandOk = $false }
}
Assert-ZbTrue $islandOk 'data island still parses as JSON with hostile descriptions embedded'
Assert-ZbTrue ($islandCsv.Contains('</script>')) 'hostile text survives the round trip into the embedded CSV'
Assert-ZbTrue (-not $smallHtml.Contains('<script>alert(1)</script>')) 'hostile description is HTML-encoded, not live markup'

# --- 5. CSV formula-injection guard ---
$csvPath = $sum.CsvFile
Assert-ZbTrue ($null -ne $csvPath -and (Test-Path -LiteralPath $csvPath)) '-Csv writes the sidecar file'
$csvText = Get-Content -LiteralPath $csvPath -Raw -Encoding UTF8
$neutralised = '"' + "'" + '=2+2'
Assert-ZbTrue ($csvText.Contains($neutralised)) 'leading = neutralised with apostrophe in CSV'
Assert-ZbEqual 0 ([regex]::Matches($csvText, '(?m)(^|,)"[=+@\t]').Count) 'no CSV cell begins with a live formula character'
Assert-ZbEqual 13 (@($csvText -split "`r`n").Count) 'CSV has header + one row per real finding'

# --- header/summary sanity that also guards the ceiling bookkeeping ---
Assert-ZbEqual 125 $sum.PhaseShortfall 'DEEP run with 8 timed phases reports a 125-phase shortfall'
Assert-ZbTrue (-not $sum.Clean) 'run with CRITICAL findings is not clean'
Assert-ZbTrue ($sum.ExecutiveSummary.Length -gt 100) 'executive summary prose was generated'

# --------------------------------------------------------------------------------------------
# 6. Comparison: baseline derived from run_small with three findings removed (they become
#    "new" in the current run) and two added (they become "resolved").
# --------------------------------------------------------------------------------------------

Write-Host 'comparison render'
$baseRecord = Get-Content -LiteralPath $smallFixture -Raw -Encoding UTF8 | ConvertFrom-Json
$removedIds = @('P07_aaa111', 'P12_ddd444', 'P99_ggg777')
$keep = @($baseRecord.Findings | Where-Object { $removedIds -notcontains $_.ID })
$added = @(
    [pscustomobject]@{
        ID = 'OLD_zzz001'; Phase = 'PHASE 12'; ThreatType = 'PERSISTENCE_RUNKEY'; Severity = 'HIGH'
        Description = 'Old run key that has since been removed.'; Target = 'HKCU:\...\Run\Old'
        FixAction = 'Info'; FixParam = ''; Group = 'PHASE 12'; Selected = $true; Timestamp = '2026-08-12 09:00:00'
    },
    [pscustomobject]@{
        ID = 'OLD_zzz002'; Phase = 'PHASE 41'; ThreatType = 'INVENTORY'; Severity = 'INFO'
        Description = 'Old inventory row no longer present.'; Target = 'n/a'
        FixAction = 'Info'; FixParam = ''; Group = 'PHASE 41'; Selected = $false; Timestamp = '2026-08-12 09:00:00'
    }
)
$baseRecord.Findings = @($keep + $added)
$baseRecord.Timestamp = '2026-08-12T09:00:00.0000000-04:00'
$baselinePath = Join-Path -Path $tempDir -ChildPath 'baseline.json'
[System.IO.File]::WriteAllText($baselinePath, (ConvertTo-Json -InputObject $baseRecord -Depth 6), $utf8NoBom)

$cmpOut = Join-Path -Path $tempDir -ChildPath 'cmp_report.html'
$sumCmp = & $renderer -Path $smallFixture -OutFile $cmpOut -MappingPath $mapFixture -Compare $baselinePath -PassThru
Assert-ZbEqual 3 $sumCmp.Comparison.NewCount 'compare: three findings new in this run'
Assert-ZbEqual 2 $sumCmp.Comparison.ResolvedCount 'compare: two findings resolved since baseline'
Assert-ZbEqual 9 $sumCmp.Comparison.PersistingCount 'compare: persisting joined on ID, GROUPCAP excluded'
Assert-ZbEqual 'worse' $sumCmp.Comparison.Verdict 'compare: serious count 3 -> 4 reads as worse'
$newSorted = @($sumCmp.Comparison.NewIds | Sort-Object)
Assert-ZbEqual 'P07_aaa111 P12_ddd444 P99_ggg777' ($newSorted -join ' ') 'compare: the new IDs are exactly the removed three'

# --------------------------------------------------------------------------------------------
# 7. Volume: 1,200 findings render in under 10 seconds and under 5 MB
# --------------------------------------------------------------------------------------------

Write-Host 'run_large render'
$largeOut = Join-Path -Path $tempDir -ChildPath 'large_report.html'
$watch = [System.Diagnostics.Stopwatch]::StartNew()
$sumLarge = & $renderer -Path $largeFixture -OutFile $largeOut -MappingPath $mapFixture -PassThru
$watch.Stop()
Assert-ZbEqual 1200 $sumLarge.TotalFindings 'large fixture: 1200 real findings'
Assert-ZbEqual 3 $sumLarge.GroupCapCount 'large fixture: 3 flood-cap markers set aside'
Assert-ZbTrue ($watch.Elapsed.TotalSeconds -lt 10) ('render time under 10s (took ' + [math]::Round($watch.Elapsed.TotalSeconds, 1) + 's)')
$largeSize = (Get-Item -LiteralPath $largeOut).Length
Assert-ZbTrue ($largeSize -lt 5MB) ('output under 5 MB (' + [math]::Round($largeSize / 1MB, 2) + ' MB)')
Assert-ZbEqual 0 $sumLarge.PhaseShortfall 'full 133-phase DEEP run reports no shortfall'

# --------------------------------------------------------------------------------------------
# 8. Empty Findings array: a valid report that says the machine is clean
# --------------------------------------------------------------------------------------------

Write-Host 'empty run render'
$emptyRecord = [pscustomobject]@{
    Timestamp       = '2026-08-19T16:00:00.0000000-04:00'
    Host            = 'WORKSTATION-11'
    User            = 'ACME\tech'
    Mode            = 'QUICK'
    TimeWindow      = 'LAST 24 HOURS'
    RiskScore       = 0
    RiskLabel       = 'CLEAN'
    Findings        = @()
    PhaseTimings    = @(1..30 | ForEach-Object { [pscustomobject]@{ Phase = ('PHASE {0}' -f $_); Seconds = 1.0 } })
    RecoveredErrors = @()
    BaselineDelta   = @()
    ThreatTally     = [pscustomobject]@{}
}
$emptyPath = Join-Path -Path $tempDir -ChildPath 'empty.json'
[System.IO.File]::WriteAllText($emptyPath, (ConvertTo-Json -InputObject $emptyRecord -Depth 6), $utf8NoBom)
$emptyOut = Join-Path -Path $tempDir -ChildPath 'empty_report.html'
$sumEmpty = & $renderer -Path $emptyPath -OutFile $emptyOut -MappingPath $mapFixture -PassThru
Assert-ZbEqual 0 $sumEmpty.TotalFindings 'empty run: zero findings'
Assert-ZbTrue ($sumEmpty.Clean) 'empty run: Clean flag set'
$emptyHtml = Get-Content -LiteralPath $emptyOut -Raw -Encoding UTF8
Assert-ZbTrue ($emptyHtml.Contains('came back clean')) 'empty run: the report says so plainly'
Assert-ZbTrue ($emptyHtml.Contains('</html>')) 'empty run: page is complete, not truncated'

# --------------------------------------------------------------------------------------------
# Input validation: a clear error up front beats a null reference three functions deep
# --------------------------------------------------------------------------------------------

Write-Host 'validation'
$noFindingsPath = Join-Path -Path $tempDir -ChildPath 'not_a_record.json'
[System.IO.File]::WriteAllText($noFindingsPath, '{ "Hello": "world" }', $utf8NoBom)
$threw = $false
try {
    & $renderer -Path $noFindingsPath -OutFile (Join-Path -Path $tempDir -ChildPath 'x.html') | Out-Null
}
catch {
    $threw = ($_.Exception.Message -like '*no Findings array*')
}
Assert-ZbTrue $threw 'JSON without a Findings array is rejected with a clear message'

$threw = $false
try {
    & $renderer -Path (Join-Path -Path $tempDir -ChildPath 'missing.json') | Out-Null
}
catch {
    $threw = ($_.Exception.Message -like '*not found*')
}
Assert-ZbTrue $threw 'missing input file is rejected with a clear message'

# --------------------------------------------------------------------------------------------
# Missing technique map: warn and render, everything unmapped
# --------------------------------------------------------------------------------------------

$noMapOut = Join-Path -Path $tempDir -ChildPath 'nomap_report.html'
$sumNoMap = & $renderer -Path $smallFixture -OutFile $noMapOut -MappingPath (Join-Path -Path $tempDir -ChildPath 'absent_map.json') -PassThru -WarningAction SilentlyContinue
Assert-ZbTrue (-not $sumNoMap.MappingLoaded) 'absent technique map is reported, not fatal'
Assert-ZbEqual 12 $sumNoMap.UnmappedCount 'absent technique map: every finding lands in Unmapped'

# --------------------------------------------------------------------------------------------
# Result
# --------------------------------------------------------------------------------------------

Remove-Item -Path $tempDir -Recurse -Force -ErrorAction SilentlyContinue
Write-Host ''
Write-Host ('{0} passed, {1} failed' -f $script:ZbPass, $script:ZbFail)
if ($script:ZbFail -gt 0) {
    Write-Host 'Failed assertions:'
    foreach ($f in $script:ZbFailures) { Write-Host ('  - ' + $f) }
    exit 1
}
exit 0
